version: "3.3"

networks:
  bridge:
    driver: bridge

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: quizapplication
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin 
    ports:
      - "5432:5432"
    networks:
      bridge:
        aliases:
          - postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  quizapplication:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      bridge:
        aliases:
          - quizapplication


volumes:
  postgres_data:
